global:
  scrape_interval: 15s     # 全局抓取间隔
  evaluation_interval: 15s # 规则评估间隔

scrape_configs:
  - job_name: 'monolith-application'
    # 路径匹配你在 application.yml 中的配置: base-path: /actuator
    metrics_path: '/actuator/prometheus'
    static_configs:
      # 这里必须修改为管理端口 9090
      - targets: ['app-server:9090']
        labels:
          env: 'production'
          service: 'ha-springboot' # 对应你的服务名