global:
  scrape_interval: 15s     # 全局抓取间隔
  evaluation_interval: 15s # 规则评估间隔

scrape_configs:
  - job_name: 'monolith-application'
    metrics_path: '/actuator/prometheus' # 指定抓取路径
    static_configs:
      # 这里填写 docker-compose 中的服务名和端口
      - targets: ['app-server:8080']
        labels:
          env: 'production'
          service: 'backend-monolith'